# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
xcode_workspace: Example/Swiftilities.xcworkspace
xcode_scheme: Swiftilities-Example
xcode_sdk: iphonesimulator10.0

after_success:
  - pod trunk push Swiftilities

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
