env:
  global:
    - LC_CTYPE=en_US.UTF-8

branches:
  only:
    - develop
    - master
    # Matching n.n.n with allowed postfix for release branches
    - /^\d+\.\d+\.\d+.*/

os: osx
language: objective-c
matrix:
  exclude:
    - os: osx
  include:
    - osx_image: xcode8
      env:
        - XCODE_ACTION="clean test"
          XCODE_TOOLCHAIN="swift"
          XCODE_DESTINATION="platform=iOS Simulator,id=237D7619-4A4E-4624-8925-67A42A8A690A"
    - osx_image: xcode8
      env:
        - JOB=CARTHAGE
      script:
        - brew update 1> /dev/null 2> /dev/null
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current
        - test -d Carthage/Build/iOS/Swiftilities.framework || exit 1

before_script:
  - killall "Simulator" || echo "No matching processes belonging to you were found"

script:
  - travis_retry xcodebuild ${XCODE_ACTION}
    -toolchain ${XCODE_TOOLCHAIN}
    -workspace Example/Swiftilities.xcworkspace
    -scheme Swiftilities-Example
    -destination "${XCODE_DESTINATION}"


deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
