version: 2

jobs:
  test:
    macos:
      xcode: "9.4.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle install
      - run:
          name: Fastlane Test
          command: |
            cd Example
            bundle exec fastlane test
      - run: bundle exec pod lib lint

  test-xcode-9-2:
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle install
      - run:
          name: Fastlane Test
          command: |
            cd Example
            bundle exec fastlane test
      - run: bundle exec pod lib lint

  carthage-build:
    macos:
      xcode: "9.4.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; HOMEBREW_NO_AUTO_UPDATE=1 brew install carthage --force-bottle)
      - run:
          name: Build with Carthage
          command: carthage build --no-skip-current && test -d Carthage/Build/iOS/Swiftilities.framework

  deploy-to-cocoapods:
    macos:
      xcode: "9.4.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install CocoaPods Specs Repo
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle install
      - run: bundle exec pod trunk push

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - test-xcode-9-2:
          filters:
            tags:
              only: /.*/
      - carthage-build:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test
            - test-xcode-9-2
            - carthage-build
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
