version: 2

jobs:
  test:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: ./scripts/iOS.sh
      - run: bundle exec pod lib lint

  carthage-build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; HOMEBREW_NO_AUTO_UPDATE=1 brew install carthage --force-bottle)
      - run:
        name: Build with Carthage
        command: carthage build --no-skip-current && test -d Carthage/Build/iOS/Swiftilities.framework || exit 1; done

  deploy-to-cocoapods:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec pod trunk push

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - carthage-build:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test
            - carthage-build
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
